-- Res-Q · surplus_posts
--
-- The one table the dashboard talks to directly: a donor logs a surplus item,
-- and every recipient sees it in their live feed until somebody claims it.
--
-- Run it in Supabase → SQL Editor → New query → Run, or keep the project linked
-- with the Supabase CLI and let `supabase db push` apply it. It is written to be
-- safe to run more than once.
--
--   psql "$DATABASE_URL" -f supabase/migrations/20261008000000_create_surplus_posts.sql


-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
-- id and created_at are generated by the database so the pages never have to
-- invent either. quantity is text on purpose: surplus is logged the way a shop
-- says it ("24 kg across 6 crates"), not as a number to do arithmetic on.
-- gen_random_uuid() is built into Postgres 13+, which every Supabase project
-- runs, so no extension is needed.
create table if not exists public.surplus_posts (
    id         uuid primary key default gen_random_uuid(),
    donor_name text not null,
    item_name  text not null,
    quantity   text not null,
    location   text not null,
    status     text not null default 'pending'
                   check (status in ('pending', 'claimed')),
    created_at timestamptz not null default now()
);

-- The feed reads newest-first and the claim works off the open rows.
create index if not exists surplus_posts_created_at_idx
    on public.surplus_posts (created_at desc);
create index if not exists surplus_posts_status_idx
    on public.surplus_posts (status);


-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- The pages hold only the publishable key, which is the anonymous role, and
-- Res-Q runs its own sign-in rather than Supabase Auth — so the table has to be
-- readable and writable by `anon`. RLS stays on with explicit policies, which
-- means the table is closed the moment these policies are dropped, and the
-- surface is exactly what the dashboard does: read the board, add a post,
-- claim a post.
alter table public.surplus_posts enable row level security;

drop policy if exists "surplus posts are public" on public.surplus_posts;
create policy "surplus posts are public"
    on public.surplus_posts for select
    to anon, authenticated
    using (true);

drop policy if exists "surplus posts accept new rows" on public.surplus_posts;
create policy "surplus posts accept new rows"
    on public.surplus_posts for insert
    to anon, authenticated
    with check (true);

drop policy if exists "surplus posts can be claimed" on public.surplus_posts;
create policy "surplus posts can be claimed"
    on public.surplus_posts for update
    to anon, authenticated
    using (true)
    with check (status in ('pending', 'claimed'));

-- Belt and braces: the policies above already gate every request, but a role
-- whose default privileges were changed elsewhere still needs the grant.
grant select, insert, update on public.surplus_posts to anon, authenticated;


-- ---------------------------------------------------------------------------
-- A claim may only change the status
-- ---------------------------------------------------------------------------
-- Claiming is the only update the dashboard ever sends, and the update policy
-- cannot say "this column only". This trigger can: an update that touches the
-- donor, the item, the quantity, the pickup location, the id or the timestamp
-- is refused outright, so a claimed row cannot be rewritten into a different
-- one and a post cannot be quietly edited after the fact.
create or replace function public.resq_surplus_posts_freeze_identity()
returns trigger
language plpgsql
as $$
begin
    if new.id is distinct from old.id
        or new.donor_name is distinct from old.donor_name
        or new.item_name is distinct from old.item_name
        or new.quantity is distinct from old.quantity
        or new.location is distinct from old.location
        or new.created_at is distinct from old.created_at then
        raise exception 'only the status of a surplus post can change';
    end if;
    return new;
end;
$$;

drop trigger if exists surplus_posts_freeze_identity on public.surplus_posts;
create trigger surplus_posts_freeze_identity
    before update on public.surplus_posts
    for each row
    execute function public.resq_surplus_posts_freeze_identity();


-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
-- New and claimed posts are pushed to every open dashboard over Supabase
-- Realtime. A table only streams once it is in the supabase_realtime
-- publication, and adding it twice is an error, so the join is made by hand.
-- The pages also re-read the table on a timer, so a project where this block
-- was skipped - because it has no such publication, or because it raised for any
-- other reason - still shows new posts, just a little later. The block is
-- guarded rather than trusting: the whole script runs as one transaction in the
-- SQL editor, so an error here would roll the table back with it.
do $$
begin
    if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
        raise notice 'no supabase_realtime publication here: the feed will re-read the table every 20 seconds instead';
    elsif not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'surplus_posts'
    ) then
        alter publication supabase_realtime add table public.surplus_posts;
    end if;
exception when others then
    raise notice 'the table was not added to supabase_realtime (%): the feed will re-read it every 20 seconds instead', sqlerrm;
end;
$$;


-- ---------------------------------------------------------------------------
-- Done
-- ---------------------------------------------------------------------------
-- The editor prints this one row when the whole script went through.
select 'surplus_posts is ready' as result;

